---
- name: install grafana recommends package
  apt:
    name:
      - software-properties-common
      - apt-transport-https
    state: present
    install_recommends: no

- name: added grafana gpg key
  apt_key:
    id: 4E40DDF6D76E284A4A6780E48C8C34C524098CB6
    url: https://packages.grafana.com/gpg.key
    state: present

- name: added grafana repository
  apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: present
