---
- name: create blackbox_exporter folders
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ blackbox_exporter.install_dir }}"
    - "{{ blackbox_exporter.config_dir }}"

- name: download blackbox_exporter
  get_url:
    url: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter.version }}/blackbox_exporter-{{ blackbox_exporter.version }}.linux-amd64.tar.gz"
    dest: '/tmp/blackbox_exporter.tar.gz'
    mode: '0644'

- name: extract blackbox_exporter.tar.gz on "{{ blackbox_exporter.install_dir }}"
  unarchive:
    src: '/tmp/blackbox_exporter.tar.gz'
    dest: "{{ blackbox_exporter.install_dir }}"
    remote_src: no
    extra_opts: [--strip-components=1]

- name: symlinks binaries on "/usr/bin"
  file:
    src: "{{ blackbox_exporter.install_dir }}/blackbox_exporter"
    dest: "/usr/bin/blackbox_exporter"
    state: link

- name: deploy configuration on "/etc/blackbox_exporter"
  template:
    src: 'blackbox.config.yml.j2'
    dest: "{{ blackbox_exporter.config_dir }}/config.yml"

- name: configure permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: 'root'
    group: 'root'
    recurse: yes
  loop:
    - "{{ blackbox_exporter.install_dir }}"
    - "{{ blackbox_exporter.config_dir }}"

- name: deploy service on "/lib/systemd/system"
  template:
    src: 'blackbox_exporter.service.j2'
    dest: '/lib/systemd/system/blackbox_exporter.service'
  notify: "reload systemd"

- name: started blackbox_exporter service
  service:
    name: blackbox_exporter
    state: started
    enabled: yes

- name: remove temp files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - '/tmp/blackbox_exporter.tar.gz'
    - "{{ blackbox_exporter.install_dir }}/blackbox.yml"
