---
- name: create prometheus group
  group:
    name: prometheus
    system: yes

- name: create prometheus user
  user:
    name: prometheus
    group: prometheus
    create_home: no
    home: /nonexistent
    shell: /usr/sbin/nologin
    password: '!'
    system: yes

- name: create prometheus folders
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ prometheus.install_dir }}"
    - "{{ prometheus.config_dir }}"
    - "{{ prometheus.rules_dir }}"
    - "{{ prometheus.data_dir }}"
