---
- name: configure permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    recurse: yes
  loop:
    - "{{ prometheus.install_dir }}"
    - "{{ prometheus.config_dir }}"
    - "{{ prometheus.data_dir }}"

- name: started prometheus service
  service:
    name: prometheus
    state: started
    enabled: yes
