---
- name: stopped alertmanager service
  service:
    name: alertmanager
    state: stopped
    enabled: no

- name: delete all directories and files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ alertmanager.install_dir }}"
    - "{{ alertmanager.config_dir }}"
    - "{{ alertmanager.data_dir | dirname }}"
    - '/lib/systemd/system/alertmanager.service'
    - '/usr/bin/alertmanager'
  notify: "reload systemd"
