# BLACKBOX EXPORTER
- name: stopped blackbox_exporter service
  service:
    name: blackbox_exporter
    state: stopped
    enabled: no

- name: remove symlinks binaries on "/usr/bin"
  file:
    path: "{{ blackbox_exporter.install_dir }}/blackbox_exporter"
    state: absent

- name: remove blackbox folders
  file:
    path: "{{ item }}"
    state: absent
    mode: '0755'
  loop:
    - "{{ blackbox_exporter.install_dir }}"
    - "{{ blackbox_exporter.config_dir }}"
    - /lib/systemd/system/blackbox_exporter.service

# NODE EXPORTER
- name: stopped node_exporter service
  service:
    name: node_exporter
    state: stopped
    enabled: no

- name: remove symlinks binaries on "/usr/bin"
  file:
    path: "{{ node_exporter.install_dir }}/node_exporter"
    state: absent

- name: remove node_exporter folders
  file:
    path: "{{ item }}"
    state: absent
    mode: '0755'
  loop:
    - "{{ node_exporter.install_dir }}"
    - /lib/systemd/system/node_exporter.service
  notify: reload systemd
